import type { Product } from './types';
const rows: Array<[string,string,Product['category'],string,string,string,string,Array<[string,number]>]> = [
['kueh-salat','Kueh Salat','Kueh','kuehsalat','A little pandan-green joy, layered over butterfly pea glutinous rice. Made for slow afternoon tea.','Glutinous rice, coconut milk, pandan, sugar, eggs, butterfly pea flower.','Eggs.',[['7 inch square',4800],['8 inch round',4800],['Half size · slicing available',2500]]],
['bingka-ubi','Bingka Ubi','Kueh','ubi','Golden on top, soft in the middle. A familiar tapioca favourite to bring to the table.','Tapioca, coconut milk, sugar, eggs, butter.','Eggs, milk.',[['9 inch square',5800],['Half size · slicing available',3000]]],
['cinnamon-rolls','Cinnamon Rolls','Bread & buns','cinnamonroll','Soft spirals with a warming cinnamon filling. Put the kettle on; these are worth sitting down for.','Wheat flour, cinnamon, sugar, butter, milk, yeast, eggs; possible walnuts.','Wheat (gluten), milk, eggs; possible tree nuts.',[['4 pieces · 3 × 3 inch each',1600]]],
['blueberry-muffins','Blueberry Muffins','Cakes & treats','blueberry','An easy breakfast, an afternoon pick-me-up, or a little something for the lunchbox.','Wheat flour, blueberries, eggs, sugar, butter, milk, baking powder.','Wheat (gluten), eggs, milk.',[['4 pieces',1600]]],
['bagels','Crusty Bagels','Bread & buns','bagel','A satisfying crust and a chewy middle. Slice, toast, and make breakfast your own.','Wheat flour, rye flour, chia seeds, yeast or sourdough starter, salt, water.','Wheat and rye (gluten).',[['4 pieces',1400]]],
['banana-cake','Divine Banana Cakes','Cakes & treats','banana','A homely banana loaf for sharing. Choose the classic, or make it a cream cheese kind of day.','Bananas, wheat flour, eggs, sugar, butter or oil, baking soda. Cream cheese version includes milk.','Wheat (gluten), eggs; milk in cream cheese version.',[['Classic · 7.5 × 4 inch',1200],['With cream cheese',1600]]],
['cranberry-walnut','Organic Cranberry Walnut','Bread & buns','cranberry','Cranberries and walnuts tucked into a rustic loaf. Lovely toasted with a little butter.','Wheat flour, cranberries, walnuts, sourdough starter, water, salt.','Wheat (gluten), walnuts (tree nuts).',[['2 pieces · 6 × 3 inch each',1000]]],
['sesame-chiffon','Black Sesame Chiffon Cake','Cakes & treats','sesame','A light chiffon cake with the nutty warmth of black sesame. A slice for everyone.','Wheat flour, black sesame, eggs, sugar, oil, milk or water.','Wheat (gluten), sesame, eggs; possible milk.',[['8 inch',2500]]],
['rustic-loaf','Warm Rustic Loaf','Bread & buns','rye','A hearty loaf with a deep crust. Tear and share at dinner, or save a slice for tomorrow.','Wheat flour, rye flour, chia and flax seeds, sourdough starter, salt, water.','Wheat and rye (gluten).',[['7 inch round',1200]]],
['sweet-potato','Sourdough Sweet Potato','Bread & buns','sweetpotato','Sweet potato and sourdough, brought together in a little bake for everyday snacking.','Wheat flour, sweet potato, sourdough starter, water, salt; possible milk and butter.','Wheat (gluten); possible milk.',[['4 pieces',800]]],
['cheese-sticks','Sourdough Cheese Sticks','Bread & buns','cheesesticks','A savoury little something for the cheese lovers at your table.','Wheat flour, cheese, sourdough starter, butter, salt.','Wheat (gluten), milk.',[['2 pieces',500]]],
['yuzu-almond','Yuzu Almond','Cakes & treats','almond','A sunny citrus cake with the gentle nuttiness of almond. Just right with a cup of tea.','Wheat flour, almond, yuzu, honey, eggs, butter, sugar.','Wheat (gluten), almonds (tree nuts), eggs, milk.',[['8 inch round',1800]]],
['pork-chives','Pork & Chives Dumplings','Dumplings','chives','Hand-folded pockets of pork and chives. Something savoury for a cosy meal at home.','Wheat flour wrappers, pork, chives, soy sauce, sesame oil, seasoning.','Wheat (gluten), soy, sesame.',[['15 pieces',1500],['30 pieces',2800]]],
['pork-cabbage','Pork & Cabbage Dumplings','Dumplings','cabbage','Pork and cabbage, wrapped up by hand. Gather around the table and share a plate.','Wheat flour wrappers, pork, cabbage, soy sauce, sesame oil, seasoning.','Wheat (gluten), soy, sesame.',[['15 pieces',1500],['30 pieces',2800]]]
];
export const seedProducts: Product[] = rows.map(([id,name,category,image,description,ingredients,allergens,variants],i)=>({id,name,category,image:`/images/${image}.jpg`,description,ingredients,allergens,ingredientsVerified:false,available:true,featured:i<3,variants:variants.map(([label,price],v)=>({id:`size-${v+1}`,label,price,salePrice:null}))}));
